# Generated by Django 3.2.3 on 2022-01-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
